server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartinstall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1332080218

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis/mybatis_config.xml
  type-aliases-package: com.xum.demo.dao
